language:
  - c
  - cpp

os:
 - linux
 - osx

env:
 - EXTRALIBS="gettext"
 - EXTRALIBS="gettext libusb-dev"
 - EXTRALIBS="gettext libusb-1.0-0-dev libgd2-xpm-dev"
 - EXTRALIBS="gettext libusb-1.0-0-dev libgd2-xpm-dev libcurl4-openssl-dev"

compiler:
 - clang
 - gcc

# On OSX, 'gcc' is an alias for 'clang' anyway, and finding/installing
# a gcc would be a bit of extra work with uncertain benefits. So on
# OSX, we only do the 'clang' builds.
jobs:
  exclude:
  - os: osx
    compiler: gcc

# Note: Keep the sudo commands in .travis.yml - they do not work from
#       a helper shell script.
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install $(sh .travis-translate-pkgs $EXTRALIBS); fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y $(sh .travis-translate-pkgs $EXTRALIBS); fi
 - automake --version
 - autoconf --version

script:
 - PATH=/usr/local/opt/gettext/bin:$PATH autoreconf -i -f && sleep 2
 - sh .travis-script.sh standard-test   --enable-vusb
 - sh .travis-script.sh everything-test --enable-vusb --with-camlibs=everything
 - date; ls -l configure
 - ./configure --enable-vusb --with-camlibs=ptp2 && make && make check && sudo PATH=$PATH make install && examples/sample-afl && make clean && sudo make uninstall

notifications:
  email:
    on_success: change
    on_failure: always
